
export function getAllProjects() {
  // console.log('>>>> getAllProjects **********************************')
  return [
    {
      name: "13z.dev",
      url: "https://13z.dev",
      summary: "My personal portfolio site",
      cldPublicId: "portfolio/portfolio-site",
      description: "I reworked most of the layout and the CSS to make previous fixed desktop design more mobile responsive, especially several modals that were not meant for mobile widths.",
      stack: "React, Next.js, TypeScript, TailwindCSS, Framer Motion, Cloudinary",
      githubUrl: "https://github.com/13zebras/personal-site-nextjs-app-router",
    },
    {
      name: "Bass Pro Shops Outdoor Fund",
      url: "https://basspro.com/cart",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/basspro-odf",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Recoil, Sass",
      githubUrl: "",
    },
    {
      name: "Doggos NFTs",
      url: "https://www.doggos.dog",
      summary: "Doggos is a successful NFT project on the Solana blockchain. The Doggos  community is strong and active.",
      cldPublicId: "portfolio/doggos-home",
      description: "I reworked most of the layout and the CSS to make previous fixed desktop design more mobile responsive, especially several modals that were not meant for mobile widths.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "BOS Shop",
      url: "https://bos-store.vercel.app",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/bos-shop",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Floating Apes Affiliation",
      url: "https://floating-apes-staking.vercel.app",
      summary: "The Floating Apes NFT project needed staking, raffle, and other services. ",
      cldPublicId: "portfolio/floating-apes",
      description: "The Floating Apes NFT project needed staking, raffle, and other services. Lucky Dog Studios provided all these services via a variety of websites.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Pet SolSociety",
      url: "https://pet-solciety-staking.vercel.app",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/pet-solciety",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Smoke Heads NFTs",
      url: "https://smoke-heads-staking.vercel.app",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/smoke-heads",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration is.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Alder Mages",
      url: "https://staking.aldermages.dev",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/alder-mages",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration is.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Arcane Valley",
      url: "https://staking.arcanevalleyproject.com/",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/arcane-valley",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration is.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "Jikan Crypto Dashboard",
      url: "https://jikan-dashboard.vercel.app",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/jikan-dashboard",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "",
    },
    {
      name: "AFI Movies NFTs",
      url: "https://solportal.13z.dev",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/afimoviesnfts",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration is.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "https://github.com/13zebras/solana-gif-portal",
    },
    {
      name: "Our Trans Kids DAO",
      url: "",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/transkidsdao",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Recoil, Sass",
      githubUrl: "https://github.com/13zebras/transkids-dao-3rdweb",
    },
    {
      name: "Renaissance Shade Solana NFTs",
      url: "",
      summary: "Renaissance Shade, an NFT collection built on Solana devnet.",
      cldPublicId: "portfolio/renaissance-shade",
      description: "The Floating Apes NFT project needed staking, raffle, and other services. Lucky Dog Studios provided all these services via a variety of websites.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "https://github.com/13zebras/solana-nft-renaissance-shade",
    },
    {
      name: "LoveLang NFT Collection",
      url: "",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/lovelang-nfts",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "https://github.com/13zebras/lovelang-nft-collection-polygon",
    },
    {
      name: "Laugh Portal Solidity",
      url: "",
      summary: "Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.",
      cldPublicId: "portfolio/laughportal",
      description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
      stack: "React, Next.js, Chakra-UI, Solana",
      githubUrl: "https://github.com/13zebras/laughportal-solidity",
    }
  ]
}