// Projects for the Portfolio page

export function getAllProjects() {
	return [
		{
			name: '13z.dev',
			url: 'https://13z.dev',
			summary: 'My personal portfolio website. It includes projects, info about me, and some of my work experience.',
			cldPublicId: 'portfolio/portfolio-site',
			description: 'I built this website to showcase projects I have created, worked on, and contributed to, as well as to share information about me and my work experience. The design and code have been inspired by others, but in the end, the responsibility for both rests squarely on my shoulders.',
			stack: 'Next.js, React, TypeScript, TailwindCSS, CSS3, Cloudinary',
			githubUrl: 'https://github.com/13zebras/personal-site-nextjs-app-router',
		},
		{
			name: 'Bass Pro Shops Outdoor Fund',
			url: 'https://basspro.com/cart',
			summary: 'The Outdoor Fund section of the Bass Pro Shops cart needed a complete overhaul to make it fully mobile responive.',
			cldPublicId: 'portfolio/basspro-odf',
			description:
				'The previous outdoor fund section of the cart was originally designed for desktop and was not mobile responsive. I reworked the layout, implemented flexbox for the entire component, and made it fully mobile responsive. I also worked with our UX team to make a new image/logo that would also be mobile responive by placing the text as an overlay on the image.',
			stack: 'React, Next.js, Recoil, Sass, Jest',
			githubUrl: '',
		},
		{
			name: 'Doggos NFTs',
			url: 'https://www.doggos.dog',
			summary: 'Doggos is an NFT project on the Solana blockchain. I helped convert their desktop only website into one that was fully mobile responsive.',
			cldPublicId: 'portfolio/doggos-home',
			description:
				"I reworked most of the layout and the CSS to make the previous fixed desktop design more mobile responsive. There were several modals, one of which was a dashboard that had a landscape orientation, that needed extensive revising. One of the biggest issues many websites face is that if you don't start mobile first, you will be in a world of hurt! I made these revisions while working at Lucky Dog Studios.",
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'BOS Shop',
			url: 'https://bos-store.vercel.app',
			summary: 'The BOS Shop was a Solana NFT project that needed a front end. I used React and Next.js to create a fully responsive website based on the projects designs.',
			cldPublicId: 'portfolio/bos-shop',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Floating Apes Affiliation',
			url: 'https://floating-apes-staking.vercel.app',
			summary: 'The Floating Apes NFT project needed staking, raffle, and other services. Lucky Dog Studios provided all these services via a variety of websites.',
			cldPublicId: 'portfolio/floating-apes',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Pet SolSociety',
			url: 'https://pet-solciety-staking.vercel.app',
			summary: 'The Pet Solciety NFT project on Solana needed a staking website. We used React and Next.js to create a staking website based on their unique designs.',
			cldPublicId: 'portfolio/pet-solciety',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Smoke Heads NFTs',
			url: 'https://smoke-heads-staking.vercel.app',
			summary: "The Smoke Heads NFT project was built on Solana and needed a staking website and more. We created a fully responsive website based on the project's designs.",
			cldPublicId: 'portfolio/smoke-heads',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Alder Mages',
			url: 'https://staking.aldermages.dev',
			summary: 'The Alder Mages NFT project needed staking, raffle, upgrade, & other services. Lucky Dog Studios created all these sites using customers designs and our smart contracts.',
			cldPublicId: 'portfolio/alder-mages',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Arcane Valley',
			url: 'https://staking.arcanevalleyproject.com/',
			summary: 'The Arcane Valley NFT project needed staking, raffle, and other services. We created these sites using customers designs with NFTs on the Solana blockchain.',
			cldPublicId: 'portfolio/arcane-valley',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'Jikan Crypto Dashboard',
			url: 'https://jikan-dashboard.vercel.app',
			summary: 'Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.',
			cldPublicId: 'portfolio/jikan-dashboard',
			description: '',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: '',
		},
		{
			name: 'AFI Movies NFTs',
			url: 'https://solportal.13z.dev',
			summary: 'Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.',
			cldPublicId: 'portfolio/afimoviesnfts',
			description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration is.",
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: 'https://github.com/13zebras/solana-gif-portal',
		},
		{
			name: 'Our Trans Kids DAO',
			url: '',
			summary: 'Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.',
			cldPublicId: 'portfolio/transkidsdao',
			description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
			stack: 'React, Next.js, Recoil, Sass',
			githubUrl: 'https://github.com/13zebras/transkids-dao-3rdweb',
		},
		{
			name: 'Renaissance Shade Solana NFTs',
			url: 'https://dummy-url.fake',
			summary: 'Renaissance Shade, an NFT collection built on Solana devnet.',
			cldPublicId: 'portfolio/renaissance-shade',
			description: 'The Floating Apes NFT project needed staking, raffle, and other services. Lucky Dog Studios provided all these services via a variety of websites.',
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: 'https://github.com/13zebras/solana-nft-renaissance-shade',
		},
		{
			name: 'LoveLang NFT Collection',
			url: '',
			summary: 'Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.',
			cldPublicId: 'portfolio/lovelang-nfts',
			description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: 'https://github.com/13zebras/lovelang-nft-collection-polygon',
		},
		{
			name: 'Laugh Portal Solidity',
			url: '',
			summary: 'Dicit dicant quaestio pri eu, no principes persecuti liberavisse sit.',
			cldPublicId: 'portfolio/laughportal',
			description: "We apply the proverb 'A rolling stone gathers no moss' not only to our power shifts but our strategic angel investors and user-proof configuration.",
			stack: 'React, Next.js, Chakra-UI, Solana',
			githubUrl: 'https://github.com/13zebras/laughportal-solidity',
		},
	]
}
