export function getAllWork() {
  return [
    {
      title: 'React Developer 2',
      employer: 'Bass Pro Shops',
      dates: 'Nov 2022 - Present',
      detailsType: 'Skills',
      details: 'React, Recoil, Next.js, Sass, Agile',
      summary1: 'Develop, refactor, & modernize basspro.com using React, Next.js, SCSS, git, and agile practices. Largest refactor: code utilizing Cloudinary APIs.',
      summary2: 'Participate in production deployments, website and database nightly builds, system monitoring and troubleshooting, and other devops type activities.',
    },
    {
      title: 'Frontend Developer',
      employer: 'Lucky Dog Studios',
      dates: 'Jan 2022 - Nov 2022',
      detailsType: 'Skills',
      details: 'React, Next.js, ChakraUI, Prisma, Solana, Supabase',
      summary1: 'Developed React frontends for NFT staking, minting, auction, and similar sites.',
      summary2: 'Clients include: Doggos.dog, BOS Shop, Alder Mages, Pet Solciety, Smoke Heads, Arcane Valley, and more (see Portfolio for details).',
    },
    {
      title: 'Math Instructor',
      employer: 'Johns Hopkins Center for Talented Youth',
      dates: 'Aug 2020 - Nov 2022',
      detailsType: 'Subjects Taught',
      details: 'Geometry & Algebra 1',
      summary1: 'Taught Geometry & Algebra online to gifted middle school and high school students throughout the country.',
      summary2: 'Worked one-on-one with students, prepared weekly lessons, graded projects and proofs, and prepared weekly reports for parents and students.',
    },
    {
      title: 'Math Teacher, Advisor',
      employer: 'Study Alternative High School',
      dates: 'Aug 2017 - Jun 2021',
      detailsType: 'Subjects Taught',
      details: 'Math, advisory, JAG',
      summary1: 'Taught math and Jobs for America’s Graduates Program (JAG) courses to high school students. Advised students on their progress toward graduation & success.',
      summary2: 'Managed a profitable, student-run t-shirt business, The Study Printing Emporium.',
    },
    {
      title: 'Self-Employed',
      employer: 'Writer, Speaker, & Wordpress Developer',
      dates: 'Jan 2008 - Aug 2011',
      detailsType: 'Skills',
      details: 'Wordpress, PHP, HTML, CSS, JavaScript',
      summary1: 'Used PHP, HTML, CSS, Wordpress, and various e-commerce tools to develop a website focused on personal growth and development.',
      summary2: 'Produced live online talks before streaming was available on platforms like Twitch and YouTube.',
    },
    {
      title: 'Self-Employed',
      employer: 'Trader and Investor',
      dates: 'Feb 1997 - Jun 2017',
      detailsType: 'Investments',
      details: 'Stocks, Bonds, Mutual Funds, ETFs, Forex',
      summary1: 'Traded forex, futures, options, stocks, and bonds for personal portfolio.',
      summary2: 'Devised trading systems and investment strategies.',
    },
    {
      title: 'BA in Biology',
      employer: 'Brown University',
      dates: 'magna cum laude',
      detailsType: '',
      details: '',
      summary1: 'Focused on molecular biology, biochemistry, and neuroscience.',
      summary2: 'Took multiple courses in European & American history, world literature, economics, physics, and chemistry.',
    },
  ]
}
